### ISSUE TITLE
.hdt.index files are incompatible with other HDT library versions

### ISSUE THREAD

**Issue by walling** [RubenVerborgh/HDT-Node#1]
When I use this module in Node, I can't open the HDT file in [HDT-it!](http://www.rdfhdt.org/download/) afterwards. Also, if I first open the HDT file in HDT-it, and I try to open it in Node aftwards, it gives an error: `[Error: Trying to read a LOGArray but data is not LogArray]`.

Is it because this module and HDT-it use different versions of the library? Is it possible to solve this somehow?

**Comment by RubenVerborgh** [comment]
As of v1.4.0, .hdt.index files now have a version number, so that they won't be in each other's way anymore.
