### ISSUE TITLE
Read/write the HDT header

### ISSUE THREAD

**Issue by LaurensRietveld** [RubenVerborgh/HDT-Node#17]
hdt-cpp allows for both writing and reading the header. Let's add that to the HDT-Node api as well

**Comment by LaurensRietveld** [comment]
An implementation detail to discuss: what triple representation do we use for the header js API. 
The nicest solution would be using N3 as dep (you may have heard about that lib).
Alternatively, we could simply support reading/writing the whole header as string, delegating the parsing/serializing to the user.

**Comment by RubenVerborgh** [comment]
I'd suggest just having text in and out, but documenting in the README how you can do things with N3.js.

**Comment by RubenVerborgh** [comment]
Implemented in #24.
