### ISSUE TITLE
Unable to build on Windows

### ISSUE THREAD

**Issue by pavelcerveny** [RubenVerborgh/HDT-Node#18]
Hi, I having a problem with building this package on Windows like system. Though I am not an expert, I guess it's because of using bash commands in binding.gyp.
To be more precise - error from console:

>  'ls' is not recognized as an internal or external command 

I was able to build it in Docker (node:latest), which I am using now as a dev enviroment, but at first I spent some time trying to figure out, what was going on.

**Comment by RubenVerborgh** [comment]
Unfortunately, hdt-cpp (on which this module depends) does not work on Windows, so I can't fix this here.
