### ISSUE TITLE
Point submodule to hdt-cpp develop branch

### ISSUE THREAD

**Issue by LaurensRietveld** [RubenVerborgh/HDT-Node#19]
What about pointing the hdt-node develop branch to the hdt-cpp one? We'd have to modify the node-gyp bindings as the hdt-cpp dir structure changed as well.

Benefits:
- The hdt-cpp develop branch will include an offsetting fix (part of https://github.com/rdfhdt/hdt-cpp/pull/147)
- We can easily release a new HDT-node version as soon as hdt-cpp is released (see https://github.com/rdfhdt/hdt-cpp/issues/150)

**Comment by LaurensRietveld** [comment]
I'm all for more patch releases of hdt-cpp :+1: .
Still, considering the next hdt-cpp release has a larger impact on HDT-node than usual (as it's more than only updating the submodule), I guess it's best to prepare an upcoming upgrade of the hdt-cpp dep by updating the bindings.gyp on the HDT-Node develop branch. Open for a PR in that respect?

**Comment by RubenVerborgh** [comment]
PR would be awesome!

**Comment by LaurensRietveld** [comment]
Great, see #20 (thanks @dinikolop ). I propose to merge this to the develop branch, and wait for hdt-cpp to be released. In the meantime we could then add a new PR to solve some offsetting issues in HDT-Node.

**Comment by RubenVerborgh** [comment]
Thanks!
