### ISSUE TITLE
Current version does not install

### ISSUE THREAD

**Issue by LaurensRietveld** [RubenVerborgh/HDT-Node#22]
There is a problem with the current version: the `deps/libcds/includes` directory is not part of the published npm package.
This omission is caused by this `.gitignore` file: https://github.com/rdfhdt/hdt-cpp/blob/develop/libcds/include/.gitignore

We'll submit a PR to hdt-cpp removing the gitignore and release a patch version. I'll leave it up to you to release the HDT-node patch version.

Reason we missed this issue is that we were testing against the HDT-Node git repo, that doesnt exclude files that `npm publish` would exclude. We _could_ consider adding `npm pack` to the travis build, and trying the install the output of that command, but not sure whether that's worth the effort

**Comment by RubenVerborgh** [comment]
Good catch. Let's indeed also do `npm pack` on Travis.

**Comment by LaurensRietveld** [comment]
Hdt-cpp has a patch release (1.3.1) with the included fix

**Comment by RubenVerborgh** [comment]
Thanks, will follow up and release a patch here as well.

**Comment by LaurensRietveld** [comment]
Ah, a note about the release: the `.gitmodule` file is still pointing to the hdt-node branch on hdt-cpp. There's no need for that anymore, so we can simply use the master branch

**Comment by RubenVerborgh** [comment]
Unpublished v2.0.1.

**Comment by RubenVerborgh** [comment]
Resolved by 33a8b7d317252768aee7e23e31dee9c9ada7c97c.
