### ISSUE TITLE
Fetch distinct predicates

### ISSUE THREAD

**Issue by dinikolop** [RubenVerborgh/HDT-Node#25]
We're writing a PR now for fetching the distinct predicates for a given object. Essentially:
```
SELECT DISTINCT ?p WHERE {?s ?p <o>} LIMIT 10
```

Before we submit the PR, we should probably agree on the JS API interface.

Our suggestion:

- Use the `searchTerms` function
- It's currently used to do prefix-based search, and takes as argument: `{limit: 1, position:'subject', prefix:'http'}`
- We suggestion adjusting `searchTerms` to support the following: 
```
searchTerms({
  position:'predicate', 
  limit: 10,
  filter: {
    position: 'object',
    value: 'some-value'
  }
})
```

Our current implementation will _only_ cover fetching the distinct predicates for a particular object. This might change in the future.

For simplicity, I suggest not to allow the user to pass a prefix _and_ a filter argument at the same time

Does that sound like a plan?

**Comment by RubenVerborgh** [comment]
Great feature!

I think the double filtering is confusing though. How about:

```
searchTerms({
  position: 'predicate', 
  limit: 10,
  object: 'some-value'
})
```

**Comment by dinikolop** [comment]
Thank you for the comment! So, the API could look more concrete as you suggested:
 
```javascript
searchTerms ({
  position: 'predicate', 
  limit: 10,
  object: 'some-value', // mutual exclusive with prefix and prioritized
  prefix: "http"        // mutual exclusive with object
})
```

This API would provide two operations:

* Searching terms of the given `position` that contain a certain given `prefix`.  (as it was till now)
* Searching distinct predicates given an `object`. If `object` is defined then the search by prefix will not be considered.

As mentioned, for now we wish to receive only _distinct predicates given an object_. In future, this might change to allow more combinations of other positions (e.g. distinct objects given a predicate etc.), but maybe the filtering would be better in this case, right? Given the other comments: https://github.com/RubenVerborgh/HDT-Node/pull/26#discussion_r169105230  https://github.com/RubenVerborgh/HDT-Node/pull/26#discussion_r169105810 
, should we stick to this suggested JS API?

**Comment by RubenVerborgh** [comment]
I would follow the suggestion without the extra `filter` for now.

**Comment by RubenVerborgh** [comment]
So #26 implements the specific case of “all predicates for given object”. However, looking at the code, I see you are iterating over all predicates and then checking whether indeed that predicate occurs with this object: 

```C++
        // Check whether a triple with this predicate and object exists
        hdt::IteratorTripleString *it = document->GetHDT()->search("", predicate, object.c_str());
        if (it->hasNext())
          distinctTerms.push_back(predicate);
```

@dinikolop Is there any specific technical reason to not also implement the “all predicates for given subject” case? (Or you just didn't need this?)

**Comment by dinikolop** [comment]
Indeed @rubensworks , as you have observed, "all predicates for a given object" are found by iterating over all predicates and matching with the object.  Through this iteration a simple check of iterator->hasNext() is set to True if the predicate shows up with the given object.  Another option was to search with a pattern of "? ? O" where O is the given object, and then transform the predicate list into a set, but this takes much more time to be estimated (due to the usually huge list of returned predicates).

To answer your question, it was not needed to implement the "for given subject" case, but the method can be extended in future in order to cover more cases. I was also wondering how the API should look like for these cases.

**Comment by RubenVerborgh** [comment]
Thanks!

> I was also wondering how the API should look like for these cases.

Just the same 😄
