### ISSUE TITLE
Update TypeScript definitions

### ISSUE THREAD

**Issue by RubenVerborgh** [RubenVerborgh/HDT-Node#27]
Following #24 and #26.

**Comment by LaurensRietveld** [comment]
Added a PR for this

ps. saw develop is now behind master. Seems the read/write header was merged to master. Was that intentional?

**Comment by RubenVerborgh** [comment]
> Added a PR for this

Thanks!

> ps. saw develop is now behind master. Seems the read/write header was merged to master. Was that intentional?

I made a mistake; fixed it now!
