### ISSUE TITLE
A Limit of 0 returns all results

### ISSUE THREAD

**Issue by mielvds** [RubenVerborgh/HDT-Node#30]
In C++, the negative of 0 is 1. This causes a problem with Limit set to 0 (no triples should ever be returned) on https://github.com/RubenVerborgh/HDT-Node/blob/master/lib/HdtDocument.cc#L165, where instead, the complete iterator is added to the vector. This causes the `countTriples()` method, which sets `limit = 0`, to be extremely inefficient. 

The main problem here is that 'no limit' is also supplied as 0. A possible solution is to encode 'no limit' as -1 or infinity.

**Comment by RubenVerborgh** [comment]
Want to try a PR where we just set the limit to 1?

**Comment by RubenVerborgh** [comment]
Closed by b5e3fc1e5cebe86a34b6d2a0f6f4b506bcfe9e59.
