### ISSUE TITLE
Fetching distinct predicates, given a subject

### ISSUE THREAD

**Issue by dinikolop** [RubenVerborgh/HDT-Node#33]
As a follow-up of issue #25 and related PR #26, we are creating another PR which contains an enhancement of `searchTerms` method. Now, it will be able to fetch a list of distinct predicates given a subject. 

Some examples of the proposed functionality are:

```JavaScript
hdtDocument.searchTerms({ object: 'http://example.org/o1', limit: 10, position: 'predicate' }) // This is already possible
hdtDocument.searchTerms({ subject: 'http://example.org/s1', limit: 10, position: 'predicate' })
hdtDocument.searchTerms({ object: 'http://example.org/o1', subject: 'http://example.org/s1', limit: 10, position: 'predicate' }) 
```
User will still not be allowed to pass `filter` while passing `object` or/and `subject` as arguments.
In future, we can add support of more combinations, e.g. fetching distinct subjects given an objects etc.

@RubenVerborgh what do you think about it?

**Comment by RubenVerborgh** [comment]
Sounds good to me, thanks for the heads-up!
