### ISSUE TITLE
Updating submodule to new hdt-cpp release

### ISSUE THREAD

**Issue by LaurensRietveld** [RubenVerborgh/HDT-Node#39]
Shall we update the release to the newest release of hdt-cpp? 
I've tested an updated hdt-cpp dep locally in hdt-node, and all works fine. 

(could submit a pr for this, but guess if you update the submodule directly that saves both of us time)

**Comment by RubenVerborgh** [comment]
Thanks, done, will release patch version if Travis is happy.
