### ISSUE TITLE
Nan API may have changed in Node 12

### ISSUE THREAD

**Issue by rubensworks** [RubenVerborgh/HDT-Node#41]
Recently, I started having Travis failures when using this lib on Node 12.
Starting from this line: https://travis-ci.org/comunica/comunica-actor-rdf-resolve-quad-pattern-hdt/jobs/527504675#L661

The same problem occurs in OSTRICH, which I still have to fix:
https://github.com/rdfostrich/ostrich-node/issues/3

Failing builds:
* https://github.com/comunica/comunica-actor-rdf-resolve-quad-pattern-hdt/issues/15
* https://github.com/comunica/comunica-actor-init-sparql-hdt/issues/66

**Comment by rubensworks** [comment]
After looking into it a bit, this seems to be a problem with Nan, as they still have to update to Node 12.
See https://github.com/nodejs/nan/issues/849

**Comment by Flarna** [comment]
I took a fast look into the error messages and there is more to do then update NAN.
e.g. at https://github.com/RubenVerborgh/HDT-Node/blob/master/lib/HdtDocument.cc#L69 there is a direct use of a v8 API which is no longer existing in NodeJs 12 (`v8::Local<v8::FunctionTemplate>::GetFunction()`).

NAN provides already an API for this in 2.13.2, e.g. use `Nan::GetFunction(constructorTemplate).ToLocalChecked()`

**Comment by mielvds** [comment]
#42 can indeed be closed. Can somebody PR this? I'm afraid I don't know NAN or c++ well enough to give it a go.

**Comment by mielvds** [comment]
Decided to take a swing at it in #43 , effort was ok in the end.
