### ISSUE TITLE
Build fails on Node 12.13.0

### ISSUE THREAD

**Issue by pheyvaer** [RubenVerborgh/HDT-Node#42]
Building the code on Node 12.13.0 fails, while it still works on 10.17.0.

**Comment by RubenVerborgh** [comment]
New version of NAN is likely to help.

**Comment by mielvds** [comment]
I can confirm the issue. Do we bump the nan version because this also blocks building the LDF server for instance.

**Comment by rubensworks** [comment]
This issue appears to be a duplicate of #41.

**Comment by mielvds** [comment]
also fixed by #43
