### ISSUE TITLE
Change HDT submodule to official repo

### ISSUE THREAD

**Issue by mielvds** [RubenVerborgh/HDT-Node#5]
Since both repos are equal now, I propose to change the submodule to https://github.com/rdfhdt/hdt-cpp and delete the LDF fork.

**Comment by RubenVerborgh** [comment]
I've just tried it, but I'm stuck with an `No implementation for CSD` error for HDTs with a literal dictionary. Will see at what point this went wrong in the hdt-cpp code.

**Comment by RubenVerborgh** [comment]
Fixed the hdt-cpp code: rdfhdt/hdt-cpp@17f5ce8f7a9d840097cc0b44738a3549546888b2.

**Comment by RubenVerborgh** [comment]
The LDF fork has also been deleted. The only repository is now https://github.com/rdfhdt/hdt-cpp.
